name: Custom Workflow Integration
on:
    push:
        branches: [ main ]
jobs:
    custom:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Run Custom Tasks
          run: npm run custom-task

        - name: Create Tag
          id: create_tag
          run: echo ::set-output name=version::moiz-v$(date +'%Y%m%d%H%M%S')
        
        - name: Push Tag
          run: |
                git tag -f ${{ steps.create_tag.outputs.version }}
                git push -f origin ${{ steps.create_tag.outputs.version }}
        
        - name: Create Release Notes
          id: create_release_notes
          uses: actions/github-script@v5
          with:
            script: |
                    const tag_name = "${{ steps.create_tag.outputs.version }}";
                    const commit_sha = process.env.GITHUB_SHA;
                    const release = {
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        tag_name: tag_name,
                        name: `Release ${tag_name}`,
                        body: `Commit: ${commit_sha}`,
                        draft: false,
                        prerelease: false
                    };
                    github.rest.repos.createRelease(release);
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}