name: Custom Workflow Integration
on:
    push:
        branches: [ main ]
jobs:
    custom:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Run Custom Tasks
          run: npm run custom-task
        - name: Create Tag
          id: create_tag
          run: echo ::set-output name=version::v$(date +%Y%m%d%H%M%S)
        - name: Push Tag
          run: |
                git tag ${{ steps.create_tag.outputs.version }}
                git push origin ${{ steps.create_tag.outputs.version }}
        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ steps.create_tag.outputs.version }}
            release_name: Release ${{ steps.create_tag.outputs.version }}
            body_path: ./CHANGELOG.md
            draft: false
            prerelease: false