name: Custom Workflow Integration
on:
    push:
        branches: [ main ]
jobs:
    custom:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Run Custom Tasks
          run: npm run custom-task
        - name: Create Tag
          run: git tag v$(date +%Y%m%d%H%M%S)
        - name: Push Tag
          run: git push origin v$(date +%Y%m%d%H%M%S)
        - name: Create Release
          uses: softprops/action-gh-release@v1
          with:
            body_path: ./CHANGELOG.md
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}