name: Custom Workflow Integration
on:
    push:
        branches: [ main ]
jobs:
    custom:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Run Custom Tasks
          run: npm run custom-task