name: Update Dependencies
on:
    schedule:
        - cron: '0 0 * * *'
jobs:
    update:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Install Dependencies
          run: npm install
        - name: Check updates
          run: npm outdated
        - name: Update dependencies
          run: npm update
        - name: Run tests
          run: npm test
        - name: Check for modified files
          id: git-check
          run: echo ::set-output name=modified::$(if git diff --staged --quiet; then echo "false"; else echo "true"; fi)
        - name: Commit changes
          if: steps.git-check.outputs.modified == 'true'
          run: |
                git config --global user.name 'github-actions[bot]'
                git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
                git commit -am 'chore: update dependencies'
        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v3
          with:
                title: 'chore: update dependencies'
                body: 'Update dependencies'
                branch: 'chore/update-dependencies'