name: Update Dependencies
on:
    push:
        branches:
            - main
jobs:
    update:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        
        - name: Install Dependencies
          run: npm install
        
        - name: Update dependencies
          run: npm update
        
        - name: Run tests
          run: npm test
        
        - name: Check for modified files
          id: git-check
          run: echo ::set-output name=modified::$(if git diff --quiet; then echo "false"; else echo "true"; fi)
        
        - name: Commit changes
          if: steps.git-check.outputs.modified == 'true'
          run: |
                git config --global user.name 'GitHub Actions'
                git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                git commit -am 'chore: update dependencies'
        
        - name: Create Pull Request
          if: steps.git-check.outputs.modified == 'true'
          uses: peter-evans/create-pull-request@v3
          with:
                title: 'chore: update dependencies'
                body: 'Update dependencies'
                branch: 'chore/update-dependencies'