name: Code Review Workflow
on:
    pull_request:
        branches: [ main ]
jobs:
    review:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Review syntax
          run: npm run lint